name: "Unit test on Ubuntu"

on:
  push:
    branches: "*"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        ruby: [2.5, 2.6, 2.7]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up package
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential mysql-client libsqlite3-dev rrdtool librrd-dev

      - name: Set up Ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Set up bundler
        run: |
          gem install bundler --no-document
          # bundle config set deployment 'true'

      - name: bundle install
        run: bundle install --jobs 4 --retry 3

      - name: test
        run: |
          bundle exec focuslight init
          bundle exec rake
